# XGB Orchestration

This notebook keeps the forecasting features built from raw 2023 daily usage data.
Cluster labels are only used to route households into cluster-specific XGB models.

In [1]:
from pathlib import Path
import os
import sys
import subprocess

REPO_NAME = "Clustering-And-Forecasting-TimeSeries-PlayingGround"
REPO_URL = "https://github.com/QuirkyCroissant/Clustering-And-Forecasting-TimeSeries-PlayingGround.git"
BRANCH = os.environ.get("NOTEBOOK_GIT_BRANCH", "main")

kaggle_root = Path("/kaggle/working")
cwd = Path.cwd().resolve()

if cwd.name == REPO_NAME and (cwd / "src" / "forecasting").exists():
    REPO_ROOT = cwd
elif kaggle_root.exists():
    repo_dir = kaggle_root / REPO_NAME
    if not repo_dir.exists():
        subprocess.run(
            ["git", "clone", "--branch", BRANCH, "--single-branch", REPO_URL, str(repo_dir)],
            check=True,
        )
    os.chdir(repo_dir)
    REPO_ROOT = repo_dir.resolve()
else:
    raise RuntimeError(
        "Could not determine REPO_ROOT automatically. Open the notebook from the repo root or run it on Kaggle."
    )

SRC_PATH = REPO_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

print("REPO_ROOT:", REPO_ROOT)
print("SRC_PATH:", SRC_PATH)

Cloning into '/kaggle/working/Clustering-And-Forecasting-TimeSeries-PlayingGround'...

REPO_ROOT: /kaggle/working/Clustering-And-Forecasting-TimeSeries-PlayingGround
SRC_PATH: /kaggle/working/Clustering-And-Forecasting-TimeSeries-PlayingGround/src

Updating files: 100% (83/83), done.

In [2]:
import json
from pathlib import Path
import pandas as pd
from IPython.display import display

from forecasting.data import (
    discover_cluster_cases,
    ensure_experiment_dirs,
    ensure_output_dirs,
    load_wide_csv,
)

OUT = ensure_output_dirs(REPO_ROOT)

TRAIN_23_PATH = REPO_ROOT / "data" / "raw" / "sample_23.csv"
TEST_24_PATH = REPO_ROOT / "data" / "raw" / "sample_24.csv"
CLUSTER_CASE_DIR = REPO_ROOT / "notebooks" / "outputs" / "feature"
SHAPELET_STATIC_PATH = REPO_ROOT / "notebooks" / "outputs" / "shapelet_experiments" / "shapelet_features.csv"

In [3]:
DEBUG = False
DEBUG_FRAC = 0.2

MODEL_NAME = "xgb"
GPU_ENABLED = True
MIN_CLUSTER_ROWS = 500
MIN_CLUSTER_HOUSEHOLDS = 30

SELECTED_CASES = ["case2", "case5"]
INCLUDE_BASE_VARIANT = True
INCLUDE_SHAPELET_STATIC_VARIANT = False

XGB_PROFILE = "regularized"
XGB_PROFILES = ["regularized", "shallow", "deeper"]
XGB_PARAMS = None
RECURSIVE_VALIDATION_ENABLED = True
RECURSIVE_VALIDATION_DAYS = 60
CLUSTER_GATING_ENABLED = True
CLUSTER_GATE_MARGIN = 0.0
INCLUDE_PROFILE_FEATURES = True
INCLUDE_SEASONAL_PRIORS = True

PLOT_SAMPLE_PER_GROUP = 2
PLOT_MAX_GROUPS = None
RANDOM_STATE = 42

In [4]:
def build_experiment_configs(case_paths: dict[str, Path]) -> list[dict]:
    case_names = SELECTED_CASES or list(case_paths)
    missing = sorted(set(case_names) - set(case_paths))
    if missing:
        raise ValueError(f"Unknown case names requested: {missing}")

    variant_defs = []
    if INCLUDE_BASE_VARIANT:
        variant_defs.append(("base", None))
    if INCLUDE_SHAPELET_STATIC_VARIANT:
        if not SHAPELET_STATIC_PATH.exists():
            raise FileNotFoundError(f"Missing shapelet static feature file: {SHAPELET_STATIC_PATH}")
        variant_defs.append(("shapelet_static", SHAPELET_STATIC_PATH))

    configs = []
    for case_name in case_names:
        for variant_name, static_path in variant_defs:
            configs.append(
                {
                    "case_name": case_name,
                    "variant_name": variant_name,
                    "experiment_name": f"{case_name}_{variant_name}",
                    "cluster_path": str(case_paths[case_name]),
                    "static_features_path": str(static_path) if static_path else None,
                }
            )
    return configs


def build_run_settings() -> dict:
    return {
        "debug": DEBUG,
        "debug_frac": DEBUG_FRAC,
        "model_name": MODEL_NAME,
        "gpu_enabled": GPU_ENABLED,
        "min_cluster_rows": MIN_CLUSTER_ROWS,
        "min_cluster_households": MIN_CLUSTER_HOUSEHOLDS,
        "xgb_profile": XGB_PROFILE,
        "xgb_profiles": XGB_PROFILES,
        "xgb_params": XGB_PARAMS,
        "recursive_validation_enabled": RECURSIVE_VALIDATION_ENABLED,
        "recursive_validation_days": RECURSIVE_VALIDATION_DAYS,
        "cluster_gating_enabled": CLUSTER_GATING_ENABLED,
        "cluster_gate_margin": CLUSTER_GATE_MARGIN,
        "include_profile_features": INCLUDE_PROFILE_FEATURES,
        "include_seasonal_priors": INCLUDE_SEASONAL_PRIORS,
        "plot_sample_per_group": PLOT_SAMPLE_PER_GROUP,
        "plot_max_groups": PLOT_MAX_GROUPS,
        "random_state": RANDOM_STATE,
    }


def run_experiment_subprocess(exp_config: dict, run_settings: dict):
    env = os.environ.copy()
    existing_pythonpath = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = str(SRC_PATH) if not existing_pythonpath else str(SRC_PATH) + os.pathsep + existing_pythonpath

    cmd = [
        sys.executable,
        "-m",
        "forecasting.experiment",
        "--repo-root",
        str(REPO_ROOT),
        "--config-json",
        json.dumps(exp_config),
        "--settings-json",
        json.dumps(run_settings),
    ]

    try:
        subprocess.run(cmd, check=True, cwd=REPO_ROOT, env=env)
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(f"Experiment failed: {exp_config['experiment_name']}") from exc


def load_experiment_metric(exp_name: str, table_name: str) -> pd.DataFrame:
    metric_path = ensure_experiment_dirs(REPO_ROOT, exp_name)["metrics"] / f"{table_name}.csv"
    if not metric_path.exists():
        raise FileNotFoundError(f"Missing metric output for {exp_name}: {metric_path}")
    return pd.read_csv(metric_path)

In [5]:
cluster_case_paths = discover_cluster_cases(CLUSTER_CASE_DIR)
experiment_configs = build_experiment_configs(cluster_case_paths)
run_settings = build_run_settings()

experiment_plan = pd.DataFrame(experiment_configs)
display(experiment_plan)
print(f"Planned experiments: {len(experiment_configs)}")

,case_name,variant_name,experiment_name,cluster_path,static_features_path
0,case2,base,case2_base,/kaggle/working/Clustering-And-Forecasting-Tim...,None
1,case5,base,case5_base,/kaggle/working/Clustering-And-Forecasting-Tim...,None

Planned experiments: 2

In [6]:
completed_experiments = []

for exp_config in experiment_configs:
    print(f"\n=== Running {exp_config['experiment_name']} ===")
    run_experiment_subprocess(exp_config, run_settings)
    completed_experiments.append(exp_config["experiment_name"])

=== Running case2_base ===

/usr/local/lib/python3.12/dist-packages/xgboost/core.py:751: UserWarning: [18:42:05] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)
Building training rows: 100%|██████████| 17547/17547 [00:41<00:00, 418.02it/s]

[0]	validation_0-mae:7.55061
[50]	validation_0-mae:3.83816
[100]	validation_0-mae:2.78396
[150]	validation_0-mae:2.57765
[200]	validation_0-mae:2.53543
[250]	validation_0-mae:2.51833
[300]	validation_0-mae:2.50383
[350]	validation_0-mae:2.49329
[400]	validation_0-mae:2.48140
[450]	validation_0-mae:2.47217
[500]	validation_0-mae:2.46216
[550]	validation_0-mae:2.45340
[600]	validation_0-mae:2.44741
[650]	validation_0-mae:2.44142
[700]	validation_0-mae:2.43455
[750]	validation_0-mae:2.42977
[800]	validation_0-mae:2.42381
[850]	validation_0-mae:2.42010
[899]	validation_0-mae:2.41715

Training xgb cluster models:   0%|          | 0/10 [00:00<?, ?it/s]

[0]	validation_0-mae:18.68745
[50]	validation_0-mae:8.41464
[100]	validation_0-mae:6.12453
[150]	validation_0-mae:5.68127
[200]	validation_0-mae:5.59270
[250]	validation_0-mae:5.53699
[300]	validation_0-mae:5.52389
[350]	validation_0-mae:5.51343
[400]	validation_0-mae:5.52134
[450]	validation_0-mae:5.54054
[500]	validation_0-mae:5.53648
[550]	validation_0-mae:5.53968
[600]	validation_0-mae:5.54052
[650]	validation_0-mae:5.54398
[700]	validation_0-mae:5.53664
[750]	validation_0-mae:5.53015
[800]	validation_0-mae:5.51915
[850]	validation_0-mae:5.51694
[899]	validation_0-mae:5.51404

Training xgb cluster models:  10%|█         | 1/10 [00:12<01:50, 12.23s/it]

[0]	validation_0-mae:9.73796
[50]	validation_0-mae:5.32023
[100]	validation_0-mae:3.75251
[150]	validation_0-mae:3.47524
[200]	validation_0-mae:3.42976
[250]	validation_0-mae:3.40039
[300]	validation_0-mae:3.38529
[350]	validation_0-mae:3.35206
[400]	validation_0-mae:3.32918
[450]	validation_0-mae:3.31452
[500]	validation_0-mae:3.30778
[550]	validation_0-mae:3.29401
[600]	validation_0-mae:3.28340
[650]	validation_0-mae:3.27533
[700]	validation_0-mae:3.26543
[750]	validation_0-mae:3.25855
[800]	validation_0-mae:3.25381
[850]	validation_0-mae:3.24522
[899]	validation_0-mae:3.23758

Training xgb cluster models:  20%|██        | 2/10 [00:27<01:50, 13.84s/it]

[0]	validation_0-mae:4.36423
[50]	validation_0-mae:2.17491
[100]	validation_0-mae:1.82031
[150]	validation_0-mae:1.76626
[200]	validation_0-mae:1.74705
[250]	validation_0-mae:1.73314
[300]	validation_0-mae:1.72079
[350]	validation_0-mae:1.71150
[400]	validation_0-mae:1.70383
[450]	validation_0-mae:1.69710
[500]	validation_0-mae:1.69188
[550]	validation_0-mae:1.68751
[600]	validation_0-mae:1.68331
[650]	validation_0-mae:1.68022
[700]	validation_0-mae:1.67722
[750]	validation_0-mae:1.67431
[800]	validation_0-mae:1.67147
[850]	validation_0-mae:1.66873
[899]	validation_0-mae:1.66678

Training xgb cluster models:  30%|███       | 3/10 [01:10<03:12, 27.48s/it]

[0]	validation_0-mae:6.48821
[50]	validation_0-mae:3.59244
[100]	validation_0-mae:2.03577
[150]	validation_0-mae:1.68086
[200]	validation_0-mae:1.64138
[250]	validation_0-mae:1.62782
[300]	validation_0-mae:1.62341
[350]	validation_0-mae:1.62219
[400]	validation_0-mae:1.61872
[450]	validation_0-mae:1.61572
[500]	validation_0-mae:1.61300
[550]	validation_0-mae:1.61317
[600]	validation_0-mae:1.61314
[650]	validation_0-mae:1.61354
[700]	validation_0-mae:1.61468
[750]	validation_0-mae:1.61602
[800]	validation_0-mae:1.61599
[850]	validation_0-mae:1.61572
[899]	validation_0-mae:1.61571

Training xgb cluster models:  40%|████      | 4/10 [01:15<01:50, 18.44s/it]

[0]	validation_0-mae:5.59593
[50]	validation_0-mae:3.11899
[100]	validation_0-mae:2.13920
[150]	validation_0-mae:1.92202
[200]	validation_0-mae:1.88501
[250]	validation_0-mae:1.85016
[300]	validation_0-mae:1.84839
[350]	validation_0-mae:1.84193
[400]	validation_0-mae:1.82744
[450]	validation_0-mae:1.82237
[500]	validation_0-mae:1.82152
[550]	validation_0-mae:1.81946
[600]	validation_0-mae:1.80242
[650]	validation_0-mae:1.79052
[700]	validation_0-mae:1.78733
[750]	validation_0-mae:1.78216
[800]	validation_0-mae:1.77917
[850]	validation_0-mae:1.77791
[899]	validation_0-mae:1.76717

Training xgb cluster models: 100%|██████████| 10/10 [01:19<00:00,  7.93s/it]
Forecasting global: 100%|██████████| 366/366 [03:27<00:00,  1.77it/s]
Forecasting by cluster: 100%|██████████| 366/366 [04:13<00:00,  1.44it/s]

=== Running case5_base ===

/usr/local/lib/python3.12/dist-packages/xgboost/core.py:751: UserWarning: [19:07:56] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)
Building training rows: 100%|██████████| 17547/17547 [00:42<00:00, 414.94it/s]

[0]	validation_0-mae:7.55061
[50]	validation_0-mae:3.83816
[100]	validation_0-mae:2.78202
[150]	validation_0-mae:2.58114
[200]	validation_0-mae:2.54017
[250]	validation_0-mae:2.52010
[300]	validation_0-mae:2.51067
[350]	validation_0-mae:2.49155
[400]	validation_0-mae:2.48298
[450]	validation_0-mae:2.47107
[500]	validation_0-mae:2.46325
[550]	validation_0-mae:2.45679
[600]	validation_0-mae:2.45117
[650]	validation_0-mae:2.44574
[700]	validation_0-mae:2.44110
[750]	validation_0-mae:2.43593
[800]	validation_0-mae:2.43187
[850]	validation_0-mae:2.42770
[899]	validation_0-mae:2.42426

Training xgb cluster models:   0%|          | 0/11 [00:00<?, ?it/s]

[0]	validation_0-mae:5.77122
[50]	validation_0-mae:2.78422
[100]	validation_0-mae:2.08560
[150]	validation_0-mae:1.97082
[200]	validation_0-mae:1.94928
[250]	validation_0-mae:1.93896
[300]	validation_0-mae:1.92706
[350]	validation_0-mae:1.91945
[400]	validation_0-mae:1.91092
[450]	validation_0-mae:1.90120
[500]	validation_0-mae:1.89260
[550]	validation_0-mae:1.88511
[600]	validation_0-mae:1.87929
[650]	validation_0-mae:1.87475
[700]	validation_0-mae:1.87031
[750]	validation_0-mae:1.86677
[800]	validation_0-mae:1.86382
[850]	validation_0-mae:1.86057
[899]	validation_0-mae:1.85750

Training xgb cluster models:   9%|▉         | 1/11 [00:15<02:30, 15.09s/it]

[0]	validation_0-mae:12.88521
[50]	validation_0-mae:6.05157
[100]	validation_0-mae:4.15723
[150]	validation_0-mae:3.81421
[200]	validation_0-mae:3.75829
[250]	validation_0-mae:3.72383
[300]	validation_0-mae:3.69967
[350]	validation_0-mae:3.68123
[400]	validation_0-mae:3.66287
[450]	validation_0-mae:3.65845
[500]	validation_0-mae:3.65360
[550]	validation_0-mae:3.65048
[600]	validation_0-mae:3.65064
[650]	validation_0-mae:3.64883
[700]	validation_0-mae:3.64755
[750]	validation_0-mae:3.64826
[800]	validation_0-mae:3.64883
[850]	validation_0-mae:3.64783
[899]	validation_0-mae:3.64819

Training xgb cluster models:  18%|█▊        | 2/11 [00:37<02:54, 19.39s/it]

[0]	validation_0-mae:4.27366
[50]	validation_0-mae:2.39172
[100]	validation_0-mae:2.02167
[150]	validation_0-mae:1.95183
[200]	validation_0-mae:1.93218
[250]	validation_0-mae:1.91132
[300]	validation_0-mae:1.89822
[350]	validation_0-mae:1.88712
[400]	validation_0-mae:1.87955
[450]	validation_0-mae:1.86959
[500]	validation_0-mae:1.86366
[550]	validation_0-mae:1.85725
[600]	validation_0-mae:1.85223
[650]	validation_0-mae:1.84827
[700]	validation_0-mae:1.84428
[750]	validation_0-mae:1.83987
[800]	validation_0-mae:1.83550
[850]	validation_0-mae:1.83251
[899]	validation_0-mae:1.82917

Training xgb cluster models:  27%|██▋       | 3/11 [01:10<03:26, 25.75s/it]

[0]	validation_0-mae:2.16457
[50]	validation_0-mae:1.54739
[100]	validation_0-mae:1.07020
[150]	validation_0-mae:0.92829
[200]	validation_0-mae:0.89325
[250]	validation_0-mae:0.88242
[300]	validation_0-mae:0.87576
[350]	validation_0-mae:0.86805
[400]	validation_0-mae:0.86188
[450]	validation_0-mae:0.86079
[500]	validation_0-mae:0.86020
[550]	validation_0-mae:0.86017
[600]	validation_0-mae:0.85875
[650]	validation_0-mae:0.85858
[700]	validation_0-mae:0.85857
[750]	validation_0-mae:0.85853
[800]	validation_0-mae:0.85853
[850]	validation_0-mae:0.85805
[899]	validation_0-mae:0.85799

Training xgb cluster models:  45%|████▌     | 5/11 [01:14<01:13, 12.27s/it]

[0]	validation_0-mae:26.15086
[50]	validation_0-mae:11.16197
[100]	validation_0-mae:6.47123
[150]	validation_0-mae:5.48257
[200]	validation_0-mae:5.26452
[250]	validation_0-mae:5.24465
[300]	validation_0-mae:5.24191
[350]	validation_0-mae:5.24202
[400]	validation_0-mae:5.24211
[450]	validation_0-mae:5.24218
[500]	validation_0-mae:5.24218
[550]	validation_0-mae:5.24220
[600]	validation_0-mae:5.24220
[650]	validation_0-mae:5.24220
[700]	validation_0-mae:5.24260
[750]	validation_0-mae:5.24261
[800]	validation_0-mae:5.24177
[850]	validation_0-mae:5.24009
[899]	validation_0-mae:5.24021
[0]	validation_0-mae:0.56961

Training xgb cluster models:  55%|█████▍    | 6/11 [01:17<00:48,  9.67s/it]

[50]	validation_0-mae:0.51865
[100]	validation_0-mae:0.50562
[150]	validation_0-mae:0.50027
[200]	validation_0-mae:0.50032
[250]	validation_0-mae:0.50028
[300]	validation_0-mae:0.50034
[350]	validation_0-mae:0.50032
[400]	validation_0-mae:0.50030
[450]	validation_0-mae:0.50025
[500]	validation_0-mae:0.50025
[550]	validation_0-mae:0.50025
[600]	validation_0-mae:0.50024
[650]	validation_0-mae:0.50024
[700]	validation_0-mae:0.50024
[750]	validation_0-mae:0.50024
[800]	validation_0-mae:0.50024
[850]	validation_0-mae:0.50024
[899]	validation_0-mae:0.50024

Training xgb cluster models:  64%|██████▎   | 7/11 [01:21<00:31,  7.76s/it]

[0]	validation_0-mae:8.50327
[50]	validation_0-mae:6.49061
[100]	validation_0-mae:5.04303
[150]	validation_0-mae:4.32252
[200]	validation_0-mae:4.28405
[250]	validation_0-mae:4.01851
[300]	validation_0-mae:3.95091
[350]	validation_0-mae:3.94733
[400]	validation_0-mae:3.91508
[450]	validation_0-mae:3.84121
[500]	validation_0-mae:3.81970
[550]	validation_0-mae:3.80865
[600]	validation_0-mae:3.79601
[650]	validation_0-mae:3.80084
[700]	validation_0-mae:3.80465
[750]	validation_0-mae:3.78249
[800]	validation_0-mae:3.77302
[850]	validation_0-mae:3.77362
[899]	validation_0-mae:3.76580

Training xgb cluster models:  73%|███████▎  | 8/11 [01:24<00:19,  6.36s/it]

[0]	validation_0-mae:2.05011
[50]	validation_0-mae:1.17437
[100]	validation_0-mae:0.97504
[150]	validation_0-mae:0.92679
[200]	validation_0-mae:0.91196
[250]	validation_0-mae:0.90438
[300]	validation_0-mae:0.90078
[350]	validation_0-mae:0.89626
[400]	validation_0-mae:0.89153
[450]	validation_0-mae:0.88881
[500]	validation_0-mae:0.88573
[550]	validation_0-mae:0.88437
[600]	validation_0-mae:0.88180
[650]	validation_0-mae:0.87921
[700]	validation_0-mae:0.87705
[750]	validation_0-mae:0.87460
[800]	validation_0-mae:0.87336
[850]	validation_0-mae:0.87263
[899]	validation_0-mae:0.87206
[0]	validation_0-mae:13.94068

Training xgb cluster models:  82%|████████▏ | 9/11 [01:27<00:10,  5.48s/it]

[50]	validation_0-mae:5.81671
[100]	validation_0-mae:3.92702
[150]	validation_0-mae:3.67242
[200]	validation_0-mae:3.62640
[250]	validation_0-mae:3.60145
[300]	validation_0-mae:3.57829
[350]	validation_0-mae:3.56194
[400]	validation_0-mae:3.57578
[450]	validation_0-mae:3.58629
[500]	validation_0-mae:3.58081
[550]	validation_0-mae:3.58116
[600]	validation_0-mae:3.59321
[650]	validation_0-mae:3.59781
[700]	validation_0-mae:3.60144
[750]	validation_0-mae:3.60475
[800]	validation_0-mae:3.61090
[850]	validation_0-mae:3.61683
[899]	validation_0-mae:3.62050

Training xgb cluster models: 100%|██████████| 11/11 [01:30<00:00,  8.22s/it]
Forecasting global: 100%|██████████| 366/366 [03:30<00:00,  1.74it/s]
Forecasting by cluster: 100%|██████████| 366/366 [04:23<00:00,  1.39it/s]

In [7]:
all_overall_summary = pd.concat(
    [load_experiment_metric(exp_name, "overall_summary") for exp_name in completed_experiments],
    ignore_index=True,
)
all_recursive_validation_summary = pd.concat(
    [load_experiment_metric(exp_name, "recursive_validation_summary") for exp_name in completed_experiments],
    ignore_index=True,
)

model_comparison = (
    all_overall_summary
    .pivot(index="experiment_name", columns="model", values="mean_mae")
    .reset_index()
)
model_comparison["delta_cluster_minus_global"] = (
    model_comparison[f"cluster_{MODEL_NAME}"] - model_comparison[f"global_{MODEL_NAME}"]
)
model_comparison = model_comparison.sort_values("delta_cluster_minus_global").reset_index(drop=True)

all_overall_summary.to_csv(OUT["metrics"] / "all_experiments_overall_summary.csv", index=False)
model_comparison.to_csv(OUT["metrics"] / "all_experiments_model_comparison.csv", index=False)
all_recursive_validation_summary.to_csv(OUT["metrics"] / "all_experiments_recursive_validation_summary.csv", index=False)

display(all_overall_summary.sort_values(["experiment_name", "model"]).reset_index(drop=True))
display(model_comparison)
display(all_recursive_validation_summary.sort_values("selected_score").reset_index(drop=True))

,n_households,mean_mae,median_mae,std_mae,mean_mape,median_mape,std_mape,model,experiment_name
0,17547,3.379981,2.085116,4.364546,329.335986,37.474228,6237.280214,cluster_xgb,case2_base
1,17547,3.398794,2.103461,4.338784,320.146661,38.176924,5044.374260,global_xgb,case2_base
2,17547,3.368432,2.071450,4.330635,308.308952,37.516991,5062.335865,cluster_xgb,case5_base
3,17547,3.413474,2.099406,4.405548,315.009034,38.179399,4997.504990,global_xgb,case5_base

model experiment_name  cluster_xgb  global_xgb  delta_cluster_minus_global
0          case5_base     3.368432    3.413474                   -0.045041
1          case2_base     3.379981    3.398794                   -0.018814

,xgb_profile,validation_days,validation_start,validation_end,global_mae,cluster_mae,gated_cluster_mae,selected_score,n_features,n_trained_cluster_models,n_allowed_cluster_models,experiment_name
0,shallow,60,2023-11-02,2023-12-31,4.414310,4.474053,4.358093,4.358093,80,9,4,case5_base
1,shallow,60,2023-11-02,2023-12-31,4.390325,4.507289,4.387534,4.387534,80,5,3,case2_base
2,regularized,60,2023-11-02,2023-12-31,4.480757,4.552854,4.463631,4.463631,80,9,4,case5_base
3,deeper,60,2023-11-02,2023-12-31,4.492372,4.528207,4.466793,4.466793,80,9,3,case5_base
4,regularized,60,2023-11-02,2023-12-31,4.485794,4.556055,4.485794,4.485794,80,5,0,case2_base
5,deeper,60,2023-11-02,2023-12-31,4.533285,4.532119,4.501036,4.501036,80,5,2,case2_base